Organizations:
  # ----- Orderer MSP -----
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: organizations/ordererOrganizations/rec.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
    OrdererEndpoints:
      - orderer.rec.com:7050

  # ----- Generator Organization MSP -----
  - &GeneratorOrg
    Name: GeneratorMSP
    ID: GeneratorMSP
    MSPDir: organizations/peerOrganizations/generator.rec.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('GeneratorMSP.admin','GeneratorMSP.peer','GeneratorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('GeneratorMSP.admin','GeneratorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('GeneratorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('GeneratorMSP.peer')"
    AnchorPeers:
      - Host: peer0.generator.rec.com
        Port: 7051

  # ----- Issuer Organization MSP -----
  - &IssuerOrg
    Name: IssuerMSP
    ID: IssuerMSP
    MSPDir: organizations/peerOrganizations/issuer.rec.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('IssuerMSP.admin','IssuerMSP.peer','IssuerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('IssuerMSP.admin','IssuerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('IssuerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('IssuerMSP.peer')"
    AnchorPeers:
      - Host: peer0.issuer.rec.com
        Port: 9051

  # ----- Buyer Organization MSP -----
  - &BuyerOrg
    Name: BuyerMSP
    ID: BuyerMSP
    MSPDir: organizations/peerOrganizations/buyer.rec.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BuyerMSP.admin','BuyerMSP.peer','BuyerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('BuyerMSP.admin','BuyerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('BuyerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('BuyerMSP.peer')"
    AnchorPeers:
      - Host: peer0.buyer.rec.com
        Port: 11051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations: []
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.rec.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.rec.com
        Port: 7050
        ClientTLSCert: organizations/ordererOrganizations/rec.com/orderers/orderer.rec.com/tls/server.crt
        ServerTLSCert: organizations/ordererOrganizations/rec.com/orderers/orderer.rec.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations: []
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  # Genesis profile untuk sistem channel orderer
  RECOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Consortiums:
      RECConsortium:
        Organizations:
          - *GeneratorOrg
          - *IssuerOrg
          - *BuyerOrg

  # Application channel profile untuk REC channel
  RECApplicationChannel:
    Consortium: RECConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *GeneratorOrg
        - *IssuerOrg
        - *BuyerOrg
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
        Endorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
      Capabilities: *ApplicationCapabilities

  # Profile untuk channel tambahan jika diperlukan
  RECMainChannel:
    Consortium: RECConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *GeneratorOrg
        - *IssuerOrg
        - *BuyerOrg
      Capabilities: *ApplicationCapabilities
