# crypto-config.yaml
# Crypto-config for Renewable Energy Certificate (REC) network
# - 1 Orderer Org
# - 3 Peer Orgs: Generator (Org1), Issuer (Org2), Buyer (Org3)
# - Each PeerOrg has 2 peers (peer0, peer1) and 1 user (Admin)
# - SANS: localhost for development/testing

OrdererOrgs:
  - Name: Orderer
    Domain: rec.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: Generator
    Domain: org1.rec.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1

  - Name: Issuer
    Domain: org2.rec.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1

  - Name: Buyer
    Domain: org3.rec.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
    Users:
      Count: 1
